name: alice_test
description: "Test utils for Alice packages."
version: 1.0.0
repository: https://github.com/jhomlala/alice
homepage: https://github.com/jhomlala/alice
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  alice:
    path: ../alice
  test: ^1.25.2
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
