name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.2.6
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  chopper: ^4.0.1
  collection: 1.18.0
  dio: 5.4.3+1
  flutter_local_notifications: 17.1.2
  http: 1.2.1
#  package_info_plus: ^2.0.0
  path_provider: 2.1.3
#  permission_handler: ^10.1.0
  rxdart: 0.27.7
  sensors_plus: 5.0.1
  share_plus: 9.0.0
#  better_player: ^0.0.83
#  open_file: ^3.2.1

dev_dependencies:
  lint: 2.3.0
