name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.2.6
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  chopper: ^4.0.1
  collection: ^1.17.1
  dio: ^5.2.1+1
  flutter_local_notifications: ^14.1.1
  http: ^1.0.0
#  package_info_plus: ^2.0.0
  path_provider: ^2.0.15
#  permission_handler: ^10.1.0
  rxdart: ^0.27.7
  sensors_plus: ^3.0.2
  share: ^2.0.4
#  better_player: ^0.0.83
#  open_file: ^3.2.1

dev_dependencies:
  lint: ^2.1.2
