name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.2.6
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0
  dio: ^5.4.1
  flutter_local_notifications: ^17.1.2
  http: ^1.2.1
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  sensors_plus: ^5.0.1
  share_plus: ^7.0.0

dev_dependencies:
  lint: ^2.3.0
